version: '3'

services:
  td_api_db:
    container_name: td_api_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: td_password 
      POSTGRES_USER: td_user
      POSTGRES_DB: td_api_postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
  td_api:
    container_name: td_api
    build:
      context: ./td_api
    stdin_open: true
    tty: true
    volumes:
      - ./td_api:/td_api
      - /Users/ridwankazi/https_certificates:/https_certificates
    environment:
      POSTGRES_PASSWORD: td_password 
      POSTGRES_USER: td_user
      POSTGRES_URL: td_api_db
      POSTGRES_DB: td_api_postgres
      FLASK_APP: app
    depends_on: 
      - td_api_db
    ports:
      - "8080:8080"