version: '3'

services:
  td_api_db:
    container_name: td_api_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: td_password 
      POSTGRES_USER: td_user
      POSTGRES_DB: td_api_postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432"
  td_api:
    container_name: td_api
    build:
      context: ./td_api
    stdin_open: true
    tty: true
    volumes:
      - ./td_api:/td_api
    environment: 
      DATABASE_URL: ""
    depends_on: 
      - td_api_db
    ports:
      # - "8080:8080"
      - "5000:5000"