FROM nickgryg/alpine-pandas:latest
# Create app directory
WORKDIR /td_api

RUN apk add --no-cache gcc musl-dev \
			libffi-dev libxml2-dev libxslt1-dev \
			libtiff4-dev libjpeg8-dev zlib1g-dev libfreetype6-dev \
			liblcms2-dev libwebp-dev tcl8.5-dev tk8.5-dev python-tk
COPY requirements.txt /td_api

RUN pip install Pillow
RUN pip install -r requirements.txt

COPY . /td_api

EXPOSE 8080

CMD ["python", "./app.py"]
