FROM python:3.6-alpine3.10
# Create app directory
WORKDIR /quickbooks

RUN apk add --no-cache gcc musl-dev

COPY requirements.txt /quickbooks

RUN pip install -r requirements.txt

COPY . /quickbooks

EXPOSE 8080

CMD ["python", "./app.py"]
