FROM nickgryg/alpine-pandas:latest
# Create app directory
WORKDIR /code

RUN apk add --no-cache gcc musl-dev \
                       jpeg-dev \
                       zlib-dev \
                       freetype-dev \
                       lcms2-dev \
                       openjpeg-dev \
                       tiff-dev \
                       tk-dev \
                       tcl-dev \
                       harfbuzz-dev \
                       fribidi-dev

COPY requirements.txt /code

RUN pip install -r requirements.txt

COPY . /code

EXPOSE 8080

CMD ["python", "./app.py"]
